version: '3.5'
services:
  postgres_db:
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:9.6
    networks:
      - marketdata_network
    ports:
      - 5555:5432
    expose:
      - "5555"
    restart: always
    tty: true
    user: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - test_db:/var/lib/postgresql/data

volumes:
  test_db:
    external: false

networks:
  marketdata_network:
    driver: bridge
    name: marketdata
